const List<String> availableStudies = [
  'Accounting and Auditing',
  'Allgemeine und vergleichende Literaturwissenschaft',
  'Angewandte Informatik',
  'Anglistik/Amerikanistik',
  'Applied IT Security',
  'Arbeits-, Organisations- und Wirtschaftspsychologie',
  'Archäologische Wissenschaften',
  'Bauingenieurwesen',
  'Biochemie',
  'Biodiversität',
  'Biologie',
  'Chemie',
  'Chinesisch',
  'Cognitive Science',
  'Computational Engineering',
  'Deutsch',
  'Development-Management',
  'Econometrics',
  'Economic Policy Consulting',
  'Elektrotechnik und Informationstechnik',
  'Empirische Mehrsprachigkeitsforschung',
  'Englisch',
  'Erziehungswissenschaft',
  'Ethics - Economics, Law and Politics',
  'European Culture and Economy (ECUE)',
  'European Master’s Programme in Human Rights and Democratisation (E.MA)',
  'Evangelische Theologie',
  'Film und audiovisuelle Medien',
  'Finance, Accounting, Auditing, Controlling & Taxation',
  'Gender Studies - Kultur, Kommunikation, Gesellschaft',
  'Geographie',
  'Geosciences',
  'Geowissenschaften',
  'Germanistik',
  'Geschichte',
  'Griechisch',
  'History, Philosophy and Culture of Science (HPS+)',
  'Human Resource Management',
  'Informatik',
  'International Gender Studies',
  'International Humanitarian Action',
  'International Political Economy of East Asia',
  'IT-Sicherheit / Informationstechnik',
  'IT-Sicherheit / Netze und Systeme',
  'Italienisch',
  'Japanisch',
  'Japanologie',
  'Katholische Theologie',
  'Klassische Archäologie',
  'Klassische Philologie',
  'Koreanistik',
  'Kriminologie, Kriminalistik und Polizeiwissenschaft',
  'Kultur, Individuum und Gesellschaft',
  'Kunstgeschichte',
  'Kunstgeschichte der Moderne und Gegenwart',
  'Lasers and Photonics',
  'Latein',
  'Linguistic Data Science',
  'Management & Consulting im Sport',
  'Management and Economics',
  'Maschinenbau',
  'Materials Science and Simulation',
  'Materialwissenschaft',
  'Mathematik',
  'Medienwissenschaft',
  'Medieval and Renaissance Studies',
  'Medizin',
  'Medizinphysik',
  'Molecular and Developmental Stem Cell Biology',
  'Molecular Science - Spectroscopy and Simulation',
  'Nationales und europäisches Wirtschaftsrecht',
  'Organizational Management',
  'Orientalistik - Islamwissenschaft',
  'Ostasienwissenschaften',
  'Pädagogik',
  'Philosophie',
  'Philosophie/praktische Philosophie',
  'Physik',
  'Politik, Wirtschaft und Gesellschaft',
  'Psychologie',
  'Public History',
  'Rechtswissenschaft',
  'Religionswissenschaft',
  'Romanische Philologie',
  'Russisch',
  'Russische Kultur',
  'Sales Engineering and Product Management',
  'Sinologie',
  'Slavische Philologie',
  'Sozialwissenschaft',
  'Spanisch',
  'Sport & Exercise Sciences for Health and Performance',
  'Sportwissenschaft',
  'Sprachen und Kulturen Ostasiens',
  'Subsurface Engineering',
  'Szenische Forschung',
  'Theaterwissenschaft',
  'Transformation of Urban Landscapes',
  'Umweltingenieurwesen',
  'Ur- und Frühgeschichte',
  'VAMoS: Computer-, Psycho- und Theoretische Linguistik',
  'Wirtschaft und Politik Ostasiens',
  'Wirtschafts- und Rohstoffarchäologie',
  'Wirtschafts- und Steuerrecht',
  'Wirtschaftswissenschaft',
];

const String firebaseDescription = '''
Um dir Benachrichtigungen über spontane Events und Termine rund um die Uni schicken zu können, verwenden wir derzeit Firebase, einen Service von Google.
Solltest du dies nicht wollen, respektieren wir das.
Im weiteren Verlauf des Jahres werden wir dafür eine Google-freie Alternative einführen.
''';

const String privacyText = '''
Um Push-Benachrichtigungen aus der Campus APP zu erhalten, bin ich damit einverstanden, dass
personenbezogene Daten (IP-Adresse, abonnierte Themen) an Server der Firma Google in die USA
übertragen werden. Mir ist bekannt, dass in den USA kein angemessenes Datenschutzniveau
gewährleistet ist und es sein kann, dass amerikanische Behörden auf diese Daten zugreifen und ich
über diesen Zugriff nicht informiert werde.
Weitere Informationen findet ihr in unserer Datenschutzerklärung.
Diese Einwilligung kann jederzeit unter „Einstellungen“ widerrufen werden.
''';

const String feedbackDescription = '''
Gestalte deine Campus App mit, ob durch
Feedback & Vorschläge, oder gar durch aktive Mitarbeit in der Entwicklung.

Folgende Kanäle stehen dir zur Verfügung,
um uns zu erreichen:
''';
