// Mocks generated by Mockito 5.4.4 from annotations
// in campus_app/test/core/auth/keycloak_auth_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:async/async.dart' as _i5;
import 'package:campus_app/core/auth/keycloak_auth_exception.dart' as _i12;
import 'package:campus_app/core/auth/keycloak_auth_repository.dart' as _i8;
import 'package:campus_app/core/auth/keycloak_auth_service.dart' as _i10;
import 'package:campus_app/core/auth/student_profile.dart' as _i11;
import 'package:jose_plus/jose.dart' as _i6;
import 'package:logging/logging.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:oidc/src/managers/user_manager.dart' as _i9;
import 'package:oidc_core/oidc_core.dart' as _i2;
import 'package:rxdart/rxdart.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOidcClientAuthentication_0 extends _i1.SmartFake
    implements _i2.OidcClientAuthentication {
  _FakeOidcClientAuthentication_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOidcStore_1 extends _i1.SmartFake implements _i2.OidcStore {
  _FakeOidcStore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOidcUserManagerSettings_2 extends _i1.SmartFake
    implements _i2.OidcUserManagerSettings {
  _FakeOidcUserManagerSettings_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBehaviorSubject_3<T> extends _i1.SmartFake
    implements _i3.BehaviorSubject<T> {
  _FakeBehaviorSubject_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_4<T> extends _i1.SmartFake
    implements _i4.StreamController<T> {
  _FakeStreamController_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOidcTokenEventsManager_5 extends _i1.SmartFake
    implements _i2.OidcTokenEventsManager {
  _FakeOidcTokenEventsManager_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncMemoizer_6<T> extends _i1.SmartFake
    implements _i5.AsyncMemoizer<T> {
  _FakeAsyncMemoizer_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJsonWebKeyStore_7 extends _i1.SmartFake
    implements _i6.JsonWebKeyStore {
  _FakeJsonWebKeyStore_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_8 extends _i1.SmartFake implements _i7.Logger {
  _FakeLogger_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOidcProviderMetadata_9 extends _i1.SmartFake
    implements _i2.OidcProviderMetadata {
  _FakeOidcProviderMetadata_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOidcPlatformSpecificOptions_10 extends _i1.SmartFake
    implements _i2.OidcPlatformSpecificOptions {
  _FakeOidcPlatformSpecificOptions_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeycloakAuthRepository_11 extends _i1.SmartFake
    implements _i8.KeycloakAuthRepository {
  _FakeKeycloakAuthRepository_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OidcUserManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockOidcUserManager extends _i1.Mock implements _i9.OidcUserManager {
  MockOidcUserManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWeb => (super.noSuchMethod(
        Invocation.getter(#isWeb),
        returnValue: false,
      ) as bool);

  @override
  _i2.OidcClientAuthentication get clientCredentials => (super.noSuchMethod(
        Invocation.getter(#clientCredentials),
        returnValue: _FakeOidcClientAuthentication_0(
          this,
          Invocation.getter(#clientCredentials),
        ),
      ) as _i2.OidcClientAuthentication);

  @override
  _i2.OidcStore get store => (super.noSuchMethod(
        Invocation.getter(#store),
        returnValue: _FakeOidcStore_1(
          this,
          Invocation.getter(#store),
        ),
      ) as _i2.OidcStore);

  @override
  _i2.OidcUserManagerSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeOidcUserManagerSettings_2(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.OidcUserManagerSettings);

  @override
  _i3.BehaviorSubject<_i2.OidcUser?> get userSubject => (super.noSuchMethod(
        Invocation.getter(#userSubject),
        returnValue: _FakeBehaviorSubject_3<_i2.OidcUser?>(
          this,
          Invocation.getter(#userSubject),
        ),
      ) as _i3.BehaviorSubject<_i2.OidcUser?>);

  @override
  _i4.StreamController<_i2.OidcEvent> get eventsController =>
      (super.noSuchMethod(
        Invocation.getter(#eventsController),
        returnValue: _FakeStreamController_4<_i2.OidcEvent>(
          this,
          Invocation.getter(#eventsController),
        ),
      ) as _i4.StreamController<_i2.OidcEvent>);

  @override
  set sessionSub(
          _i4.StreamSubscription<_i2.OidcMonitorSessionResult>? _sessionSub) =>
      super.noSuchMethod(
        Invocation.setter(
          #sessionSub,
          _sessionSub,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.OidcTokenEventsManager get tokenEvents => (super.noSuchMethod(
        Invocation.getter(#tokenEvents),
        returnValue: _FakeOidcTokenEventsManager_5(
          this,
          Invocation.getter(#tokenEvents),
        ),
      ) as _i2.OidcTokenEventsManager);

  @override
  set currentDiscoveryDocument(
          _i2.OidcProviderMetadata? _currentDiscoveryDocument) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentDiscoveryDocument,
          _currentDiscoveryDocument,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.AsyncMemoizer<void> get initMemoizer => (super.noSuchMethod(
        Invocation.getter(#initMemoizer),
        returnValue: _FakeAsyncMemoizer_6<void>(
          this,
          Invocation.getter(#initMemoizer),
        ),
      ) as _i5.AsyncMemoizer<void>);

  @override
  set initMemoizer(_i5.AsyncMemoizer<void>? _initMemoizer) =>
      super.noSuchMethod(
        Invocation.setter(
          #initMemoizer,
          _initMemoizer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.StreamSubscription<dynamic>> get toDispose => (super.noSuchMethod(
        Invocation.getter(#toDispose),
        returnValue: <_i4.StreamSubscription<dynamic>>[],
      ) as List<_i4.StreamSubscription<dynamic>>);

  @override
  _i6.JsonWebKeyStore get keyStore => (super.noSuchMethod(
        Invocation.getter(#keyStore),
        returnValue: _FakeJsonWebKeyStore_7(
          this,
          Invocation.getter(#keyStore),
        ),
      ) as _i6.JsonWebKeyStore);

  @override
  _i7.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_8(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i7.Logger);

  @override
  _i2.OidcProviderMetadata get discoveryDocument => (super.noSuchMethod(
        Invocation.getter(#discoveryDocument),
        returnValue: _FakeOidcProviderMetadata_9(
          this,
          Invocation.getter(#discoveryDocument),
        ),
      ) as _i2.OidcProviderMetadata);

  @override
  set discoveryDocument(_i2.OidcProviderMetadata? value) => super.noSuchMethod(
        Invocation.setter(
          #discoveryDocument,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get didInit => (super.noSuchMethod(
        Invocation.getter(#didInit),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> get initFuture => (super.noSuchMethod(
        Invocation.getter(#initFuture),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.OidcAuthorizeResponse?> getAuthorizationResponse(
    _i2.OidcProviderMetadata? metadata,
    _i2.OidcAuthorizeRequest? request,
    _i2.OidcPlatformSpecificOptions? options,
    Map<String, dynamic>? preparationResult,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthorizationResponse,
          [
            metadata,
            request,
            options,
            preparationResult,
          ],
        ),
        returnValue: _i4.Future<_i2.OidcAuthorizeResponse?>.value(),
      ) as _i4.Future<_i2.OidcAuthorizeResponse?>);

  @override
  _i4.Future<_i2.OidcEndSessionResponse?> getEndSessionResponse(
    _i2.OidcProviderMetadata? metadata,
    _i2.OidcEndSessionRequest? request,
    _i2.OidcPlatformSpecificOptions? options,
    Map<String, dynamic>? preparationResult,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEndSessionResponse,
          [
            metadata,
            request,
            options,
            preparationResult,
          ],
        ),
        returnValue: _i4.Future<_i2.OidcEndSessionResponse?>.value(),
      ) as _i4.Future<_i2.OidcEndSessionResponse?>);

  @override
  _i4.Stream<_i2.OidcFrontChannelLogoutIncomingRequest>
      listenToFrontChannelLogoutRequests(
    Uri? listenOn,
    _i2.OidcFrontChannelRequestListeningOptions? options,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #listenToFrontChannelLogoutRequests,
              [
                listenOn,
                options,
              ],
            ),
            returnValue:
                _i4.Stream<_i2.OidcFrontChannelLogoutIncomingRequest>.empty(),
          ) as _i4.Stream<_i2.OidcFrontChannelLogoutIncomingRequest>);

  @override
  _i4.Stream<_i2.OidcMonitorSessionResult> monitorSessionStatus({
    required Uri? checkSessionIframe,
    required _i2.OidcMonitorSessionStatusRequest? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorSessionStatus,
          [],
          {
            #checkSessionIframe: checkSessionIframe,
            #request: request,
          },
        ),
        returnValue: _i4.Stream<_i2.OidcMonitorSessionResult>.empty(),
      ) as _i4.Stream<_i2.OidcMonitorSessionResult>);

  @override
  Map<String, dynamic> prepareForRedirectFlow(
          _i2.OidcPlatformSpecificOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareForRedirectFlow,
          [options],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Stream<_i2.OidcUser?> userChanges() => (super.noSuchMethod(
        Invocation.method(
          #userChanges,
          [],
        ),
        returnValue: _i4.Stream<_i2.OidcUser?>.empty(),
      ) as _i4.Stream<_i2.OidcUser?>);

  @override
  _i4.Stream<_i2.OidcEvent> events() => (super.noSuchMethod(
        Invocation.method(
          #events,
          [],
        ),
        returnValue: _i4.Stream<_i2.OidcEvent>.empty(),
      ) as _i4.Stream<_i2.OidcEvent>);

  @override
  Never logAndThrow(
    String? message, {
    Map<String, dynamic>? extra = const {},
    Object? error,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAndThrow,
          [message],
          {
            #extra: extra,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValue: null,
      ) as Never);

  @override
  void ensureInit() => super.noSuchMethod(
        Invocation.method(
          #ensureInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getSerializableOptions(
          _i2.OidcPlatformSpecificOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSerializableOptions,
          [options],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.OidcPlatformSpecificOptions getPlatformOptions(
          [_i2.OidcPlatformSpecificOptions? optionsOverride]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlatformOptions,
          [optionsOverride],
        ),
        returnValue: _FakeOidcPlatformSpecificOptions_10(
          this,
          Invocation.method(
            #getPlatformOptions,
            [optionsOverride],
          ),
        ),
      ) as _i2.OidcPlatformSpecificOptions);

  @override
  _i4.Future<_i2.OidcUser?> loginAuthorizationCodeFlow({
    _i2.OidcProviderMetadata? discoveryDocumentOverride,
    Uri? redirectUriOverride,
    Uri? originalUri,
    List<String>? scopeOverride,
    List<String>? promptOverride,
    List<String>? uiLocalesOverride,
    String? displayOverride,
    List<String>? acrValuesOverride,
    dynamic extraStateData,
    bool? includeIdTokenHintFromCurrentUser = true,
    String? idTokenHintOverride,
    String? loginHint,
    Duration? maxAgeOverride,
    Map<String, dynamic>? extraParameters,
    Map<String, dynamic>? extraTokenParameters,
    Map<String, String>? extraTokenHeaders,
    _i2.OidcPlatformSpecificOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginAuthorizationCodeFlow,
          [],
          {
            #discoveryDocumentOverride: discoveryDocumentOverride,
            #redirectUriOverride: redirectUriOverride,
            #originalUri: originalUri,
            #scopeOverride: scopeOverride,
            #promptOverride: promptOverride,
            #uiLocalesOverride: uiLocalesOverride,
            #displayOverride: displayOverride,
            #acrValuesOverride: acrValuesOverride,
            #extraStateData: extraStateData,
            #includeIdTokenHintFromCurrentUser:
                includeIdTokenHintFromCurrentUser,
            #idTokenHintOverride: idTokenHintOverride,
            #loginHint: loginHint,
            #maxAgeOverride: maxAgeOverride,
            #extraParameters: extraParameters,
            #extraTokenParameters: extraTokenParameters,
            #extraTokenHeaders: extraTokenHeaders,
            #options: options,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<_i2.OidcUser?> loginPassword({
    required String? username,
    required String? password,
    List<String>? scopeOverride,
    _i2.OidcProviderMetadata? discoveryDocumentOverride,
    Map<String, dynamic>? extraBodyFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginPassword,
          [],
          {
            #username: username,
            #password: password,
            #scopeOverride: scopeOverride,
            #discoveryDocumentOverride: discoveryDocumentOverride,
            #extraBodyFields: extraBodyFields,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<_i2.OidcUser?> tryGetAuthResponse({
    required _i2.OidcAuthorizeRequest? request,
    required String? grantType,
    required _i2.OidcPlatformSpecificOptions? options,
    required _i2.OidcProviderMetadata? metadata,
    required Map<String, dynamic>? prep,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryGetAuthResponse,
          [],
          {
            #request: request,
            #grantType: grantType,
            #options: options,
            #metadata: metadata,
            #prep: prep,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<_i2.OidcUser?> loginImplicitFlow({
    required List<String>? responseType,
    _i2.OidcProviderMetadata? discoveryDocumentOverride,
    Uri? redirectUriOverride,
    Uri? originalUri,
    List<String>? scopeOverride,
    List<String>? promptOverride,
    List<String>? uiLocalesOverride,
    String? displayOverride,
    List<String>? acrValuesOverride,
    dynamic extraStateData,
    bool? includeIdTokenHintFromCurrentUser = true,
    String? idTokenHintOverride,
    String? loginHint,
    Duration? maxAgeOverride,
    Map<String, dynamic>? extraParameters,
    _i2.OidcPlatformSpecificOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginImplicitFlow,
          [],
          {
            #responseType: responseType,
            #discoveryDocumentOverride: discoveryDocumentOverride,
            #redirectUriOverride: redirectUriOverride,
            #originalUri: originalUri,
            #scopeOverride: scopeOverride,
            #promptOverride: promptOverride,
            #uiLocalesOverride: uiLocalesOverride,
            #displayOverride: displayOverride,
            #acrValuesOverride: acrValuesOverride,
            #extraStateData: extraStateData,
            #includeIdTokenHintFromCurrentUser:
                includeIdTokenHintFromCurrentUser,
            #idTokenHintOverride: idTokenHintOverride,
            #loginHint: loginHint,
            #maxAgeOverride: maxAgeOverride,
            #extraParameters: extraParameters,
            #options: options,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<void> forgetUser() => (super.noSuchMethod(
        Invocation.method(
          #forgetUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> revokeAccessToken({
    _i2.OidcProviderMetadata? discoveryDocumentOverride,
    _i2.OidcPlatformSpecificOptions? options,
    bool? forgetUser = true,
    String? overrideAccessToken,
    Uri? revocationEndpointOverride,
    Map<String, dynamic>? extraBodyFields,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeAccessToken,
          [],
          {
            #discoveryDocumentOverride: discoveryDocumentOverride,
            #options: options,
            #forgetUser: forgetUser,
            #overrideAccessToken: overrideAccessToken,
            #revocationEndpointOverride: revocationEndpointOverride,
            #extraBodyFields: extraBodyFields,
            #headers: headers,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> revokeRefreshToken({
    _i2.OidcProviderMetadata? discoveryDocumentOverride,
    _i2.OidcPlatformSpecificOptions? options,
    bool? forgetUser = true,
    String? overrideRefreshToken,
    Uri? revocationEndpointOverride,
    Map<String, dynamic>? extraBodyFields,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeRefreshToken,
          [],
          {
            #discoveryDocumentOverride: discoveryDocumentOverride,
            #options: options,
            #forgetUser: forgetUser,
            #overrideRefreshToken: overrideRefreshToken,
            #revocationEndpointOverride: revocationEndpointOverride,
            #extraBodyFields: extraBodyFields,
            #headers: headers,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout({
    String? logoutHint,
    Map<String, dynamic>? extraParameters,
    _i2.OidcPlatformSpecificOptions? options,
    Uri? postLogoutRedirectUriOverride,
    Uri? originalUri,
    dynamic extraStateData,
    List<String>? uiLocalesOverride,
    _i2.OidcProviderMetadata? discoveryDocumentOverride,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
          {
            #logoutHint: logoutHint,
            #extraParameters: extraParameters,
            #options: options,
            #postLogoutRedirectUriOverride: postLogoutRedirectUriOverride,
            #originalUri: originalUri,
            #extraStateData: extraStateData,
            #uiLocalesOverride: uiLocalesOverride,
            #discoveryDocumentOverride: discoveryDocumentOverride,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> handleEndSessionResponse(
          {required _i2.OidcEndSessionResponse? result}) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleEndSessionResponse,
          [],
          {#result: result},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.OidcUser?> handleSuccessfulAuthResponse({
    required _i2.OidcAuthorizeResponse? response,
    required String? grantType,
    required _i2.OidcProviderMetadata? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleSuccessfulAuthResponse,
          [],
          {
            #response: response,
            #grantType: grantType,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<_i2.OidcUser?> createUserFromToken({
    required _i2.OidcToken? token,
    required String? nonce,
    required Map<String, dynamic>? attributes,
    required Map<String, dynamic>? userInfo,
    required _i2.OidcProviderMetadata? metadata,
    bool? validateAndSave = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserFromToken,
          [],
          {
            #token: token,
            #nonce: nonce,
            #attributes: attributes,
            #userInfo: userInfo,
            #metadata: metadata,
            #validateAndSave: validateAndSave,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<void> saveUser(_i2.OidcUser? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void listenToUserSessionIfSupported(_i2.OidcUser? user) => super.noSuchMethod(
        Invocation.method(
          #listenToUserSessionIfSupported,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.OidcUser?> refreshToken({
    String? overrideRefreshToken,
    _i2.OidcProviderMetadata? discoveryDocumentOverride,
    Map<String, dynamic>? extraBodyFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
          {
            #overrideRefreshToken: overrideRefreshToken,
            #discoveryDocumentOverride: discoveryDocumentOverride,
            #extraBodyFields: extraBodyFields,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<void> listenToTokenRefreshIfSupported(
    _i2.OidcTokenEventsManager? tokenEventsManager,
    _i2.OidcUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenToTokenRefreshIfSupported,
          [
            tokenEventsManager,
            user,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> handleTokenExpiring(_i2.OidcToken? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleTokenExpiring,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void handleTokenExpired(_i2.OidcToken? event) => super.noSuchMethod(
        Invocation.method(
          #handleTokenExpired,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Exception> validateUser({
    required _i2.OidcUser? user,
    required _i2.OidcProviderMetadata? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateUser,
          [],
          {
            #user: user,
            #metadata: metadata,
          },
        ),
        returnValue: <Exception>[],
      ) as List<Exception>);

  @override
  _i4.Future<_i2.OidcUser?> validateAndSaveUser({
    required _i2.OidcUser? user,
    required _i2.OidcProviderMetadata? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateAndSaveUser,
          [],
          {
            #user: user,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);

  @override
  _i4.Future<void> cleanUpStore(
          {required Set<_i2.OidcStoreNamespace>? toDelete}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanUpStore,
          [],
          {#toDelete: toDelete},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> ensureDiscoveryDocument() => (super.noSuchMethod(
        Invocation.method(
          #ensureDiscoveryDocument,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadCachedTokens() => (super.noSuchMethod(
        Invocation.method(
          #loadCachedTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> loadStateResult() => (super.noSuchMethod(
        Invocation.method(
          #loadStateResult,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> loadLogoutRequests() => (super.noSuchMethod(
        Invocation.method(
          #loadLogoutRequests,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> clearUnusedStates() => (super.noSuchMethod(
        Invocation.method(
          #clearUnusedStates,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> handleFrontChannelLogoutRequest(
          _i2.OidcFrontChannelLogoutIncomingRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleFrontChannelLogoutRequest,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.OidcUser?> reAuthorizeUser() => (super.noSuchMethod(
        Invocation.method(
          #reAuthorizeUser,
          [],
        ),
        returnValue: _i4.Future<_i2.OidcUser?>.value(),
      ) as _i4.Future<_i2.OidcUser?>);
}

/// A class which mocks [OidcStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockOidcStore extends _i1.Mock implements _i2.OidcStore {
  MockOidcStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setMany(
    _i2.OidcStoreNamespace? namespace, {
    required Map<String, String>? values,
    String? managerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMany,
          [namespace],
          {
            #values: values,
            #managerId: managerId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeMany(
    _i2.OidcStoreNamespace? namespace, {
    required Set<String>? keys,
    String? managerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMany,
          [namespace],
          {
            #keys: keys,
            #managerId: managerId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Set<String>> getAllKeys(
    _i2.OidcStoreNamespace? namespace, {
    String? managerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [namespace],
          {#managerId: managerId},
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<Map<String, String>> getMany(
    _i2.OidcStoreNamespace? namespace, {
    required Set<String>? keys,
    String? managerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMany,
          [namespace],
          {
            #keys: keys,
            #managerId: managerId,
          },
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);
}

/// A class which mocks [KeycloakAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeycloakAuthService extends _i1.Mock
    implements _i10.KeycloakAuthService {
  MockKeycloakAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.KeycloakAuthRepository get keycloakAuthRepository => (super.noSuchMethod(
        Invocation.getter(#keycloakAuthRepository),
        returnValue: _FakeKeycloakAuthRepository_11(
          this,
          Invocation.getter(#keycloakAuthRepository),
        ),
      ) as _i8.KeycloakAuthRepository);

  @override
  _i4.Stream<_i11.StudentProfile?> get userChanges => (super.noSuchMethod(
        Invocation.getter(#userChanges),
        returnValue: _i4.Stream<_i11.StudentProfile?>.empty(),
      ) as _i4.Stream<_i11.StudentProfile?>);

  @override
  _i4.Stream<_i12.KeycloakSessionExpiredException> get sessionFailures =>
      (super.noSuchMethod(
        Invocation.getter(#sessionFailures),
        returnValue: _i4.Stream<_i12.KeycloakSessionExpiredException>.empty(),
      ) as _i4.Stream<_i12.KeycloakSessionExpiredException>);

  @override
  _i4.Future<_i11.StudentProfile?> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<_i11.StudentProfile?>.value(),
      ) as _i4.Future<_i11.StudentProfile?>);

  @override
  _i4.Future<_i11.StudentProfile?> login() => (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
        ),
        returnValue: _i4.Future<_i11.StudentProfile?>.value(),
      ) as _i4.Future<_i11.StudentProfile?>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
